### ISSUE TITLE
Add configuration for base folder

### ISSUE THREAD

**Issue by fetzi** [karriereat/php-code-quality#5]
All used tools are executed for the `src` folder.

This source code folder should be configurable. Maybe in a yaml file in the project directory.

**Comment by jaylinski** [comment]
Limiting the folder to `src` was an intentional decision, because this package focuses on testing libraries. `src` is the standard source-code-folder for libraries.

What's your use case?

**Comment by fetzi** [comment]
Using the code quality package in a Laravel project! 😉
